# config/packages/security.yaml
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        in_memory: { memory: null }

    firewalls:
        # Désactiver la sécurité pour les routes de développement
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Firewall principal
        main:
            lazy: true
            provider: in_memory
            # Authentification via HTTP Basic
            http_basic: ~  # Vous pouvez remplacer cela par json_login, form_login, etc., selon votre besoin
            # Vous pouvez ajouter des options supplémentaires comme le remember_me, logout, etc.

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
